[build]
  base = "Scout-FrontEnd"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://scout-backend-d0f9.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
